
<?php
$this->title = "My Albums";
$this->headTitle($this->title);
?>

<table id ='person' class ='tbl2' border='1'>
    <thead>
        <tr>
            <th><b> Airline </b></th>
            <th><b> Flight </b></th>
            <th><b> City, State </b></th>
            <th><b> Date, Time </b></th>
            <th><b> Status </b></th>
            <th><b> Gate </b></th>
            <th><b> Bag Claim </b></th>
        </tr>
    </thead>

    <?php foreach ($this->arrivalflightschedule as $singleschedule) : ?>
        <tbody>
            <tr>
                <td class='airline'> <?php echo $singleschedule->Airline; ?> </td>
                <td class='flightNumber'> <?php echo $singleschedule->FlightNumber; ?> </td>
                <td class='cityState'> 
                    <?php echo $singleschedule->CityState; ?>           
                    <input type="button" class="mapHideBtn" onclick="hideMap()" value="Hide"/>
                    <input type="button" class="mapShowBtn" onclick="showMap('<?php echo $singleschedule->CityState; ?>', '<?php echo $singleschedule->idNum; ?>')" value="Map"/>   
                </td>

                <td class='dateTime'> <?php echo $singleschedule->DateTime; ?> </td>
                <td class='status'> <?php echo $singleschedule->Status; ?> </td>
                <td class='gate'> <?php echo $singleschedule->Gate; ?> </td>
                <td class='baggage'> <?php echo $singleschedule->Baggage; ?>  </td>
            </tr>  
            <tr id="<?php echo $singleschedule->CityState; ?>', '<?php echo $singleschedule->idNum; ?>" class="mapRow"><td colspan="7"><div id="<?php echo $singleschedule->CityState; ?>', '<?php echo $singleschedule->idNum; ?>" ></div><td></tr>
        </tbody>
    <?php endforeach; ?>

</table>

