<p>Welcome to my website. You can search flight
    information of Denver International Airport (DIA) <br></p>


<br>
<p>Current time is
    Please check the time above to see if the flight database is current.</p>

<p>I recommend that you update the flight database
    before starting your search since flight information changes constantly
</p>
<br /><br />

<div>
    <div class="box1 red">
        <p id="progressbar1"></p>
        <p class="ajaxPart1"> Click this box <br/><br/>Update Departure Flight Database</p>
    </div>

    <div class="box1 green" >
        <p id="progressbar2"></p>
        <p class="ajaxPart2">Click this box <br/><br/>Update Arrival Flight Database</p>
    </div>
</div>