<div id="searchForm"> 
    <h2>Search a specific airline
        with specific flight number<br /></h2><br /><br />
    <?php
    echo $this->departureairlineflightnumberform;
    ?> 
<h1 id = "timesubmit"> testett </h1>

</div>

Airline <input type="text" name="airline" id="airline" />
Flight Number <input type="text" name="flight" id="flight" />

<button type="button" id="filterBtn" >Filter</button>


<div id="displayairlineandtimeresult">
    
</div>

