<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework Tutorial');
echo $this->doctype();
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/jquery-ui.css'); ?>  
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/menustyle.css'); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/mystyle.css'); ?>  
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/panning-slideshow.css'); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/tablestyle.css'); ?>

        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/diaJS.js'); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/dropDownMenu.js'); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/image-rotator.js'); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-1.6.2.min.js'); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui-1.8.5.custom.js'); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.min.js'); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery.easing.js'); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery.timer.js'); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/mapJS.js'); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/tablePlugin.js'); ?>

        <style type="text/css">
            .ui-progressbar-value { background-image: url(images/pbar-ani.gif); }
        </style>
    </head>

    <div id="container" >
        <body>
            <table border="0" >
                <td width="750" height="200">
                    <?php include("fixPieces_webPage/head.php"); ?>                   
                </td>
                <td>
                    <? include("fixPieces_webPage/weather.php"); ?>
                </td>      
            </table>
<h1> DIA Flight Search Services</h1> <br>
            <table border="0">
                <tr>
                    <td >                                               
                        <?php include("fixPieces_webPage/headMenu.php"); ?>
                    </td>
                </tr>
                <tr>
                    <td>                            
                        <?php echo $this->layout()->content; ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <address> <?php include("fixPieces_webPage/buttomMenu.php"); ?> </address>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php include("fixPieces_webPage/foot.php"); ?>
                    </td>
                </tr>
            </table> 
        </body> 
    </div>

</html>